### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Found interface org.apache.spark.sql.catalyst.catalog.ExternalCatalog, but class was expected

### ISSUE THREAD

**Issue by gadongji** [hortonworks-spark/spark-atlas-connector#205]
Hi,
We are trying the hook on Databricks cluster and get the following exception at the first attempt to create a table:

java.lang.IncompatibleClassChangeError: Found interface org.apache.spark.sql.catalyst.catalog.ExternalCatalog, but class was expected
                at com.hortonworks.spark.atlas.sql.SparkCatalogEventProcessor.process(SparkCatalogEventProcessor.scala:62)
                at com.hortonworks.spark.atlas.sql.SparkCatalogEventProcessor.process(SparkCatalogEventProcessor.scala:30)
                at com.hortonworks.spark.atlas.AbstractEventProcessor$$anonfun$eventProcess$1.apply(AbstractEventProcessor.scala:67)
                at com.hortonworks.spark.atlas.AbstractEventProcessor$$anonfun$eventProcess$1.apply(AbstractEventProcessor.scala:66)
                at scala.Option.foreach(Option.scala:257)
                at com.hortonworks.spark.atlas.AbstractEventProcessor.eventProcess(AbstractEventProcessor.scala:66)
                at com.hortonworks.spark.atlas.AbstractEventProcessor$$anon$1.run(AbstractEventProcessor.scala:39)

We have tested both Spark 2.4.0 and 2.3.1 but the exception keeps the same. Is this a known issue or what should we do to resolve this? Thanks.

**Comment by HeartSaVioR** [comment]
@gadongji 
First of all, thanks for reporting! 
Could you test this from vanilla (Apache) version of Spark 2.4.0? And could you also specify which branch/commit you used to test? The stack trace doesn't represent current master branch.

**Comment by gadongji** [comment]
@HeartSaVioR 
We used this release: https://github.com/hortonworks-spark/spark-atlas-connector/releases/tag/v0.1.0-2.3-1.0.0 .
Please let me know if there is any known issue with this release or any possible solution for the exception we got.
