### ISSUE TITLE
Run SAC in pyspark sql, and got "Cannot find active or default SparkSession in the current context"

### ISSUE THREAD

**Issue by luzhonghao** [hortonworks-spark/spark-atlas-connector#211]
I ran a sql query in pyspark, and got the following exception:
  `>>> spark.sql("create table test_db.tbl2 as select * from test_db.tbl1")`
19/03/29 21:17:28 WARN SparkCatalogEventTracker:  Caught exception during parsing catalog event
java.lang.IllegalStateException: Cannot find active or default SparkSession in the current context
	at com.hortonworks.spark.atlas.utils.SparkUtils$.sparkSession(SparkUtils.scala:35)
	at com.hortonworks.spark.atlas.utils.SparkUtils$.getExternalCatalog(SparkUtils.scala:87)
	at com.hortonworks.spark.atlas.sql.SparkCatalogEventTracker$$anonfun$eventProcess$2.apply(SparkCatalogEventTracker.scala:120)
	at com.hortonworks.spark.atlas.sql.SparkCatalogEventTracker$$anonfun$eventProcess$2.apply(SparkCatalogEventTracker.scala:96)
	at scala.Option.foreach(Option.scala:257)
	at com.hortonworks.spark.atlas.sql.SparkCatalogEventTracker.eventProcess(SparkCatalogEventTracker.scala:96)
	at com.hortonworks.spark.atlas.sql.AbstractService$$anon$1.run(AbstractService.scala:24)
DataFrame[]

The exception is from [here](https://github.com/hortonworks-spark/spark-atlas-connector/blob/master/spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/utils/SparkUtils.scala#L32). @dongjoon-hyun Could you please help to look at this issue? Thanks.

**Comment by iamrjt04** [comment]
Can you get the solution for this?
