### ISSUE TITLE
Error occur when run in

### ISSUE THREAD

**Issue by sajiayixiao** [hortonworks-spark/spark-atlas-connector#280]

**Comment by sajiayixiao** [comment]
when i use spark-submit to run the jar, error occur. 

19/10/10 18:11:44 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, dbus-n1, 45817, None)
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.atlas.ApplicationProperties.get()Lorg/apache/commons/configuration/Configuration;
        at com.hortonworks.spark.atlas.AtlasClientConf.configuration$lzycompute(AtlasClientConf.scala:25)
        at com.hortonworks.spark.atlas.AtlasClientConf.configuration(AtlasClientConf.scala:25)
        at com.hortonworks.spark.atlas.AtlasClientConf.get(AtlasClientConf.scala:50)
        at com.hortonworks.spark.atlas.AtlasClient$.atlasClient(AtlasClient.scala:120)
        at com.hortonworks.spark.atlas.SparkAtlasEventTracker.<init>(SparkAtlasEventTracker.scala:33)
        at com.hortonworks.spark.atlas.SparkAtlasEventTracker.<init>(SparkAtlasEventTracker.scala:37)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.spark.util.Utils$$anonfun$loadExtensions$1.apply(Utils.scala:2691)
        at org.apache.spark.util.Utils$$anonfun$loadExtensions$1.apply(Utils.scala:2680)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
        at org.apache.spark.util.Utils$.loadExtensions(Utils.scala:2680)
        at org.apache.spark.SparkContext$$anonfun$setupAndStartListenerBus$1.apply(SparkContext.scala:2387)
        at org.apache.spark.SparkContext$$anonfun$setupAndStartListenerBus$1.apply(SparkContext.scala:2386)
        at scala.Option.foreach(Option.scala:257)
        at org.apache.spark.SparkContext.setupAndStartListenerBus(SparkContext.scala:2386)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:555)
        at AvgAgeCalculator$.main(AvgAgeCalculator.scala:12)
        at AvgAgeCalculator.main(AvgAgeCalculator.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/10/10 18:11:44 INFO DiskBlockManager: Shutdown hook called.

Any suggestion will be appreciated.

**Comment by long1208** [comment]
hi，
Is there a reason for this problem?

**Comment by sajiayixiao** [comment]
no,  no solution！

**Comment by chinaboyll** [comment]
jar is too more，Unable to identify which to use ，--jars To specify a
jar包整多了，识别不到使用哪个包。--jars 指定少一些。
