### ISSUE TITLE
can't load file atlas-application.properties

### ISSUE THREAD

**Issue by romandata** [hortonworks-spark/spark-atlas-connector#284]
1. I put the atlas-application.properties to $SPARK_HOME/conf at all of spark node .
2. bin/spark-shell --jars spark-atlas-connector_2.11-0.1.0-SNAPSHOT.jar --conf spark.extraListeners=com.hortonworks.spark.atlas.SparkAtlasEventTracker --conf spark.sql.queryExecutionListeners=com.hortonworks.spark.atlas.SparkAtlasEventTracker --conf spark.sql.streaming.streamingQueryListeners=com.hortonworks.spark.atlas.SparkAtlasStreamingQueryEventTracker --files conf/atlas-application.properties .
3. add atlas-application.properties into atlas-intg-2.0.0.jar and spark-atlas-connector_2.11-0.1.0-SNAPSHOT.jar .

but, it is error of _Failed to load application properties_ when I start spark application.

What should I do? please...

**Comment by DataRoman** [comment]
Caused by: org.apache.commons.configuration.ConversionException: 'atlas.graph.index.search.solr.wait-searcher' doesn't map to a List object: true, a java.lang.Boolean
	at org.apache.commons.configuration.AbstractConfiguration.getList(AbstractConfiguration.java:1144)
	at org.apache.commons.configuration.AbstractConfiguration.getList(AbstractConfiguration.java:1109)
	at org.apache.commons.configuration.AbstractConfiguration.interpolatedConfiguration(AbstractConfiguration.java:1274)
	at org.apache.atlas.ApplicationProperties.get(ApplicationProperties.java:129)
	... 85 more

**Comment by RonBarabash** [comment]
@DataRoman did u managed to fix this? can u please share the solution?
