### ISSUE TITLE
Run SAC in pyspark, and got "Cannot find active or default SparkSession in the current context"

### ISSUE THREAD

**Issue by weiqingy** [hortonworks-spark/spark-atlas-connector#32]
I ran a sql query in pyspark, and got the following exception:
```
>>> spark.sql("create table tmp_case_q (key INT, value STRING)")
18/03/05 20:20:20 WARN SparkCatalogEventTracker:  Caught exception during parsing catalog event
java.lang.IllegalStateException: Cannot find active or default SparkSession in the current context
	at com.hortonworks.spark.atlas.utils.SparkUtils$.sparkSession(SparkUtils.scala:35)
	at com.hortonworks.spark.atlas.utils.SparkUtils$.getExternalCatalog(SparkUtils.scala:87)
	at com.hortonworks.spark.atlas.sql.SparkCatalogEventTracker$$anonfun$eventProcess$2.apply(SparkCatalogEventTracker.scala:120)
	at com.hortonworks.spark.atlas.sql.SparkCatalogEventTracker$$anonfun$eventProcess$2.apply(SparkCatalogEventTracker.scala:96)
	at scala.Option.foreach(Option.scala:257)
	at com.hortonworks.spark.atlas.sql.SparkCatalogEventTracker.eventProcess(SparkCatalogEventTracker.scala:96)
	at com.hortonworks.spark.atlas.sql.AbstractService$$anon$1.run(AbstractService.scala:24)
DataFrame[]
```
The exception is from [here](https://github.com/hortonworks-spark/spark-atlas-connector/blob/master/spark-atlas-connector/src/main/scala/com/hortonworks/spark/atlas/utils/SparkUtils.scala#L32). @jerryshao Could you please help to look at this issue? Thanks.

cc: @dongjoon-hyun

**Comment by weiqingy** [comment]
Resolved in HWX spark side.

**Comment by SimonWan1029** [comment]
Same Problem,How to resolve that problem; Whats the meaning of 'HWX spark side'?

**Comment by luzhonghao** [comment]
@weiqingy I meet the same problem, can you tell me how to resolve the problem, thank you

**Comment by srinivasugaddam** [comment]
@weiqingy   I meet the same problem, can you tell me how to resolve the problem, thank you

**Comment by iamrjt04** [comment]
@SimonWan1029 HWX(stands for hortonworks).
@weiqingy instead of pyspark use spark-shell or spark-submit(use spark-session of java or scala),
as SAC code is written in scala and unable to fetch active or default SparkSession from python since up to my knowledge it is able to search only in java environment(JVM).
