### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/atlas/ApplicationProperties

### ISSUE THREAD

**Issue by roberthambleytech** [hortonworks-spark/spark-atlas-connector#65]
I am getting the following error when running the spark-shell:

```
$  spark-shell --jars spark-atlas-connector_2.11-0.1.0-SNAPSHOT.jar --conf spark.extraListeners=com.hortonworks.spark.atlas.SparkAtlasEventTracker --conf spark.sql.queryExecutionListeners=com.hortonworks.spark.atlas.SparkAtlasEventTracker
SPARK_MAJOR_VERSION is set to 2, using Spark2
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
java.lang.NoClassDefFoundError: org/apache/atlas/ApplicationProperties
  at com.hortonworks.spark.atlas.AtlasClientConf.configuration$lzycompute(AtlasClientConf.scala:27)
  at com.hortonworks.spark.atlas.AtlasClientConf.configuration(AtlasClientConf.scala:27)
  at com.hortonworks.spark.atlas.AtlasClientConf.get(AtlasClientConf.scala:52)
  at com.hortonworks.spark.atlas.AtlasClient$.atlasClient(AtlasClient.scala:88)
  at com.hortonworks.spark.atlas.SparkAtlasEventTracker.<init>(SparkAtlasEventTracker.scala:39)
  at com.hortonworks.spark.atlas.SparkAtlasEventTracker.<init>(SparkAtlasEventTracker.scala:43)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at org.apache.spark.util.Utils$$anonfun$loadExtensions$1.apply(Utils.scala:2743)
  at org.apache.spark.util.Utils$$anonfun$loadExtensions$1.apply(Utils.scala:2732)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
  at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:74)
  at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
  at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
  at org.apache.spark.util.Utils$.loadExtensions(Utils.scala:2732)
  at org.apache.spark.SparkContext$$anonfun$setupAndStartListenerBus$1.apply(SparkContext.scala:2360)
  at org.apache.spark.SparkContext$$anonfun$setupAndStartListenerBus$1.apply(SparkContext.scala:2359)
  at scala.Option.foreach(Option.scala:257)
  at org.apache.spark.SparkContext.setupAndStartListenerBus(SparkContext.scala:2359)
  at org.apache.spark.SparkContext.<init>(SparkContext.scala:554)
  at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2493)
  at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:930)
  at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:921)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:921)
  at org.apache.spark.repl.Main$.createSparkSession(Main.scala:103)
  ... 55 elided
Caused by: java.lang.ClassNotFoundException: org.apache.atlas.ApplicationProperties
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 84 more
<console>:14: error: not found: value spark
       import spark.implicits._
              ^
<console>:14: error: not found: value spark
       import spark.sql
              ^
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.3.0.2.6.5.0-292
      /_/

Using Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_112)
Type in expressions to have them evaluated.
Type :help for more information.

scala> 
```

**Comment by roberthambleytech** [comment]
Atlas version is .8

**Comment by LeszekLeszczynski** [comment]
I have the same issue. Any progress on this?

**Comment by krisss85** [comment]
@roberthambleytech have you used assembly jar with all the dependencies?

**Comment by merlintang** [comment]
@roberthambleytech  any update on this issue?

**Comment by dongjoon-hyun** [comment]
Hi, all. Please reopen this if this is reproducible in the latest clusters.

**Comment by zincob** [comment]
Is it possible to re-open this issue?
I'm facing the same issue with Atlas 0.8 and Spark 2.3

**Comment by dongjoon-hyun** [comment]
Ur, @zincob .

Sorry, but no. We already moved forward to Atlas 1.1 and Spark 2.4. Spark 2.3 will be EOF in several months.
- https://github.com/hortonworks-spark/spark-atlas-connector/blob/master/pom.xml#L32-L33
```
<spark.version>2.4.0</spark.version>
<atlas.version>1.1.0</atlas.version>
```

**Comment by akshaymukherjee** [comment]
This error is still coming in aws emr for Atlas 1.0 and Spark 2.4, any update?

java.lang.NoClassDefFoundError: org/apache/atlas/ApplicationProperties
  at com.hortonworks.spark.atlas.AtlasClientConf.configuration$lzycompute(AtlasClientConf.scala:25)
  at com.hortonworks.spark.atlas.AtlasClientConf.configuration(AtlasClientConf.scala:25)
  at com.hortonworks.spark.atlas.AtlasClientConf.get(AtlasClientConf.scala:50)
  at com.hortonworks.spark.atlas.AtlasClient$.atlasClient(AtlasClient.scala:120)
  at com.hortonworks.spark.atlas.SparkAtlasEventTracker.<init>(SparkAtlasEventTracker.scala:37)
  at com.hortonworks.spark.atlas.SparkAtlasEventTracker.<init>(SparkAtlasEventTracker.scala:41)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  at org.apache.spark.util.Utils$$anonfun$loadExtensions$1.apply(Utils.scala:2691)
  at org.apache.spark.util.Utils$$anonfun$loadExtensions$1.apply(Utils.scala:2680)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
  at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
  at org.apache.spark.util.Utils$.loadExtensions(Utils.scala:2680)
  at org.apache.spark.SparkContext$$anonfun$setupAndStartListenerBus$1.apply(SparkContext.scala:2387)
  at org.apache.spark.SparkContext$$anonfun$setupAndStartListenerBus$1.apply(SparkContext.scala:2386)
  at scala.Option.foreach(Option.scala:257)
  at org.apache.spark.SparkContext.setupAndStartListenerBus(SparkContext.scala:2386)
  at org.apache.spark.SparkContext.<init>(SparkContext.scala:555)
  at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2520)
  at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:935)
  at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:926)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:926)
  at org.apache.spark.repl.Main$.createSparkSession(Main.scala:106)
  ... 62 elided
Caused by: java.lang.ClassNotFoundException: org.apache.atlas.ApplicationProperties
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by aasthaTS** [comment]
use uber(assembly) jar and not spark-atlas-connector_2.11-0.1.0-SNAPSHOT.jar, that will fix the issue.

**Comment by lyyprean** [comment]
> Atlas版本是.8

你好，你的问题解决了吗

**Comment by lyyprean** [comment]
> Atlas version is .8



> I am getting the following error when running the spark-shell:
> 
> ```
> $  spark-shell --jars spark-atlas-connector_2.11-0.1.0-SNAPSHOT.jar --conf spark.extraListeners=com.hortonworks.spark.atlas.SparkAtlasEventTracker --conf spark.sql.queryExecutionListeners=com.hortonworks.spark.atlas.SparkAtlasEventTracker
> SPARK_MAJOR_VERSION is set to 2, using Spark2
> Setting default log level to "WARN".
> To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
> java.lang.NoClassDefFoundError: org/apache/atlas/ApplicationProperties
>   at com.hortonworks.spark.atlas.AtlasClientConf.configuration$lzycompute(AtlasClientConf.scala:27)
>   at com.hortonworks.spark.atlas.AtlasClientConf.configuration(AtlasClientConf.scala:27)
>   at com.hortonworks.spark.atlas.AtlasClientConf.get(AtlasClientConf.scala:52)
>   at com.hortonworks.spark.atlas.AtlasClient$.atlasClient(AtlasClient.scala:88)
>   at com.hortonworks.spark.atlas.SparkAtlasEventTracker.<init>(SparkAtlasEventTracker.scala:39)
>   at com.hortonworks.spark.atlas.SparkAtlasEventTracker.<init>(SparkAtlasEventTracker.scala:43)
>   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>   at org.apache.spark.util.Utils$$anonfun$loadExtensions$1.apply(Utils.scala:2743)
>   at org.apache.spark.util.Utils$$anonfun$loadExtensions$1.apply(Utils.scala:2732)
>   at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
>   at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
>   at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:74)
>   at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
>   at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
>   at org.apache.spark.util.Utils$.loadExtensions(Utils.scala:2732)
>   at org.apache.spark.SparkContext$$anonfun$setupAndStartListenerBus$1.apply(SparkContext.scala:2360)
>   at org.apache.spark.SparkContext$$anonfun$setupAndStartListenerBus$1.apply(SparkContext.scala:2359)
>   at scala.Option.foreach(Option.scala:257)
>   at org.apache.spark.SparkContext.setupAndStartListenerBus(SparkContext.scala:2359)
>   at org.apache.spark.SparkContext.<init>(SparkContext.scala:554)
>   at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2493)
>   at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:930)
>   at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:921)
>   at scala.Option.getOrElse(Option.scala:121)
>   at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:921)
>   at org.apache.spark.repl.Main$.createSparkSession(Main.scala:103)
>   ... 55 elided
> Caused by: java.lang.ClassNotFoundException: org.apache.atlas.ApplicationProperties
>   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>   ... 84 more
> <console>:14: error: not found: value spark
>        import spark.implicits._
>               ^
> <console>:14: error: not found: value spark
>        import spark.sql
>               ^
> Welcome to
>       ____              __
>      / __/__  ___ _____/ /__
>     _\ \/ _ \/ _ `/ __/  '_/
>    /___/ .__/\_,_/_/ /_/\_\   version 2.3.0.2.6.5.0-292
>       /_/
> 
> Using Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_112)
> Type in expressions to have them evaluated.
> Type :help for more information.
> 
> scala> 
> ```

Hello, have you solved this problem
