### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.atlas.type.AtlasTypeUtil.createClassTypeDef(

### ISSUE THREAD

**Issue by mohitjn19** [hortonworks-spark/spark-atlas-connector#66]
Following error occurs while using atlas 1.0 =>

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.atlas.type.AtlasTypeUtil.createClassTypeDef(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/Set;[Lorg/apache/atlas/model/typedef/AtlasStructDef$AtlasAttributeDef;)Lorg/apache/atlas/model/typedef/AtlasEntityDef;
        at com.hortonworks.spark.atlas.types.metadata$.<init>(metadata.scala:43)
        at com.hortonworks.spark.atlas.types.metadata$.<clinit>(metadata.scala)
        at com.hortonworks.spark.atlas.types.SparkAtlasModel$.<init>(SparkAtlasModel.scala:42)
        at com.hortonworks.spark.atlas.types.SparkAtlasModel$.<clinit>(SparkAtlasModel.scala)
        at com.hortonworks.spark.atlas.SparkAtlasEventTracker.initializeSparkModel(SparkAtlasEventTracker.scala:108)
        at com.hortonworks.spark.atlas.SparkAtlasEventTracker.<init>(SparkAtlasEventTracker.scala:48)
        at com.hortonworks.spark.atlas.SparkAtlasEventTracker.<init>(SparkAtlasEventTracker.scala:39)
        at com.hortonworks.spark.atlas.SparkAtlasEventTracker.<init>(SparkAtlasEventTracker.scala:43)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.spark.util.Utils$$anonfun$loadExtensions$1.apply(Utils.scala:2743)
        at org.apache.spark.util.Utils$$anonfun$loadExtensions$1.apply(Utils.scala:2732)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:74)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
        at org.apache.spark.util.Utils$.loadExtensions(Utils.scala:2732)
        at org.apache.spark.SparkContext$$anonfun$setupAndStartListenerBus$1.apply(SparkContext.scala:2360)
        at org.apache.spark.SparkContext$$anonfun$setupAndStartListenerBus$1.apply(SparkContext.scala:2359)
        at scala.Option.foreach(Option.scala:257)
        at org.apache.spark.SparkContext.setupAndStartListenerBus(SparkContext.scala:2359)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:554)
        at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2493)
        at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:933)
        at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:924)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:924)
        at com.oi.hermes.impl.SplineDemo$.main(SplineDemo.scala:18)
        at com.oi.hermes.impl.SplineDemo.main(SplineDemo.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:906)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:197)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:227)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by merlintang** [comment]
thanks for your update, can you give more details about this?

**Comment by merlintang** [comment]
it seems this is related to altas version issue and class mismatch.

**Comment by mohitjn19** [comment]
Yes, it was the version issue.

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by merlintang** [comment]
@mohitjn19  can you give me more details about your test env, like altas version, spark version etc.

**Comment by dongjoon-hyun** [comment]
We are using Apache Atlas 1.1.0 and Apache Spark 2.4.0. I cannot reproduce this issue now.
