### ISSUE TITLE
Unable to get lineage for Structured streaming

### ISSUE THREAD

**Issue by nagarajjayakumar** [hortonworks-spark/spark-atlas-connector#78]
Unable to get lineage for the Structured streaming. is this implemented ? if yes can you please provide us the branch ?

**Comment by nagarajjayakumar** [comment]
getting the following exception while running the Spark streaming example

Caught exception during parsing event
scala.MatchError: {
  "description" : "KafkaSource[Subscribe[in_topic_demo1]]",
  "startOffset" : {
    "in_topic_demo1" : {
      "0" : 13
    }
  },
  "endOffset" : {
    "in_topic_demo1" : {
      "0" : 13
    }
  },
  "numInputRows" : 0,
  "processedRowsPerSecond" : 0.0
} (of class org.apache.spark.sql.streaming.SourceProgress)
	at com.hortonworks.spark.atlas.sql.SparkStreamingQueryEventProcessor$$anonfun$1.apply(SparkStreamingQueryEventProcessor.scala:34)
	at com.hortonworks.spark.atlas.sql.SparkStreamingQueryEventProcessor$$anonfun$1.apply(SparkStreamingQueryEventProcessor.scala:34)

**Comment by nagarajjayakumar** [comment]
PLease ignore
